### Get all products
GET http://localhost:3000/products

### Get single product by id
GET http://localhost:3000/products/6a5deaaa238cd869568fdc9c

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "LICH Coaster Set",
  "description": "Set of 4 3D printed geometric coasters",
  "category": "Home Decor",
  "material": "PLA",
  "color": "Various",
  "printTimeHours": 5,
  "price": 220,
  "inStock": true
}

### Get all orders
GET http://localhost:3000/orders

### Get single order by id
GET http://localhost:3000/orders/6a5f52a9f2062e4a3b072152

### Create an order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "customerName": "Lerato Sithole",
  "email": "lerato@example.com",
  "productId": "6a5f6a7efc82b9c9b81a604a",
  "quantity": 1,
  "status": "pending",
  "orderDate": "2026-07-21"
}

### Update a product
PUT http://localhost:3000/products/6a5f6a7efc82b9c9b81a604a
Content-Type: application/json

{
  "name": "Cosmic Phone Case",
  "description": "Updated precision-fit case with new grip texture",
  "category": "Phone Accessories",
  "material": "TPU",
  "color": "Lavender",
  "printTimeHours": 4,
  "price": 300,
  "inStock": true
}

### Delete a product
DELETE http://localhost:3000/products/6a5f6a7efc82b9c9b81a604a

### Update an order
PUT http://localhost:3000/orders/6a5feea6ba0777cf61aa08c4
Content-Type: application/json

{
  "customerName": "Lerato Sithole",
  "email": "lerato@updated.com",
  "productId": "6a5feea6ba0777cf61aa08c4",
  "quantity": 2,
  "status": "shipped",
  "orderDate": "2026-07-21"
}

### Delete an order
DELETE http://localhost:3000/orders/6a5fedffba0777cf61aa08c3